# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Hidropixel
                                 A QGIS plugin
 This is just a test"
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-29
        copyright            : (C) 2023 by João Vitor & Adriano Rolim
        email                : jvds@academico.ufpb.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from qgis.PyQt.QtWidgets import QMessageBox
import sys
import importlib.util


def classFactory(iface):  # pylint: disable=invalid-name
    """Load Hidropixel class from file Hidropixel.

    This function is called by QGIS to instantiate the plugin. If
    dependencies are missing, return a DummyPlugin that does nothing.
    """
    # All dependencies present: import and instantiate the real plugin
    from .hidropixel import Hidropixel
    return Hidropixel(iface)
